version: '3'
services:
  mongodb:
    image: mongo
    # can add env variables as part of the container and not the image : 
    #environment:
    #  - MONGO_DB_USERNAME=admin
    #  - MONGO_DB_PWS=password
    ports:
      - 27017:27017
  api-test:
    build:
      context: ./
    ports:
      - 3000:3000
    command: node ./home/app/server.js
    depends_on:
      - mongodb
    links:
      - mongodb